#!/usr/bin/python3
""" Some dictionaries to map user readable symbols into shift reg pins and so on...
"""

from state import *

shiftRegDict = {'A': {State.Vol:       ((4,0),
                                        (4,1),
                                        (4,2),
                                        (4,3),
                                        (4,4),
                                        (4,5)),
                      State.Tone:      ((4,6),
                                        (4,7),
                                        (5,0),
                                        (5,1)),
                      State.ToneRange: ((5,2),),
                      State.Inverter:  ((5,3),
                                        (5,4))},
                'B': {State.Vol:       ((5,5),
                                        (5,6),
                                        (5,7),
                                        (6,0),
                                        (6,1),
                                        (6,2)),
                      State.Tone:      ((6,3),
                                        (6,4),
                                        (6,5),
                                        (6,6)),
                      State.ToneRange: ((6,7),),
                      State.Inverter:    ((7,0),
                                          (7,1))},
                'C': {State.Vol:       ((7,2),
                                        (7,3),
                                        (7,4),
                                        (7,5),
                                        (7,6),
                                        (7,7)),
                      State.Tone:      ((8,0),
                                        (8,1),
                                        (8,2),
                                        (8,3)),
                      State.ToneRange: ((8,4),),
                      State.Inverter:    ((8,5),
                                          (8,6))},
                'D': {State.Vol:       ((8,7),
                                        (9,0),
                                        (9,1),
                                        (9,2),
                                        (9,3),
                                        (9,4)),
                      State.Tone:      ((9,5),
                                        (9,6),
                                        (9,7),
                                        (10,0)),
                      State.ToneRange: ((10,1),),
                      State.Inverter:    ((10,2),
                                          (10,3))},
                'M': {State.Vol:       ((10,4),
                                        (10,5),
                                        (10,6),
                                        (10,7),
                                        (11,0),
                                        (11,1)),
                      State.Tone:      ((11,2),
                                        (11,3),
                                        (11,4),
                                        (11,5)),
                      State.ToneRange: ((11,6),
                                        (11,7),
                                        (12,0),
                                        (12,1),
                                        (12,2))}}

maskingDict = {'A' : {State.Vol         : ((4,0B11000000),),
                      State.Tone        : ((4,0B00111111),(5,0B11111100)),
                      State.ToneRange   : ((5,0B11111011),),
                      State.Inverter    : ((5,0B11100111),)},
               'B' : {State.Vol         : ((5,0B00011111), (6,0B11111000)),
                      State.Tone        : ((6,0B10000111),),
                      State.ToneRange   : ((6,0B01111111),),
                      State.Inverter    : ((7,0B11111100),)},
               'C' : {State.Vol         : ((7,0B00000011),),
                      State.Tone        : ((8,0B11110000),),
                      State.ToneRange   : ((8,0B11101111),),
                      State.Inverter    : ((8,0B10011111),)},
               'D' : {State.Vol         : ((8,0B01111111), (9,0B11100000)),
                      State.Tone        : ((9,0B00011111), (10,0B11111110)),
                      State.ToneRange   : ((10,0B11111101),),
                      State.Inverter    : ((10,0B11110011),)},
               'M' : {State.Vol         : ((10,0B00001111), (11,0B11111100)),
                      State.Tone        : ((11,0B11000011),),
                      State.ToneRange   : ((11,0B00111111), (12,0B00000000))}}

               

    
